import { useState, useEffect, useRef, useCallback } from 'react';
import { useAppStore } from '../store/useAppStore';

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */

function formatDuration(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, '0')}`;
}

function formatDurationLong(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  if (m === 0) return `${s} seconds`;
  return `${m} minute${m !== 1 ? 's' : ''} ${s} second${s !== 1 ? 's' : ''}`;
}

/* ------------------------------------------------------------------ */
/*  Mock data for the demo                                             */
/* ------------------------------------------------------------------ */

const MOCK_HISTORY = [
  { id: '1', label: 'Yesterday', duration: '18 min', calm: 85, prompts: 2, extra: 'Shared with Dr. Thompson \u2713' },
  { id: '2', label: '2 days ago', duration: '22 min', calm: 71, prompts: 5, extra: '' },
  { id: '3', label: '3 days ago', duration: '12 min', calm: 92, prompts: 1, extra: '\u2B50 Best session this week' },
];

const MOCK_KEY_MOMENTS = [
  '2:14 \u2014 Tone rose slightly during transition discussion',
  '5:30 \u2014 You used a calm redirect \u2014 Leo responded well',
  '8:45 \u2014 Leo signed \u2018more\u2019 \u2014 great recognition!',
];

const MOCK_SIGNS = ['more', 'help', 'all done', 'happy'];

/* ------------------------------------------------------------------ */
/*  PDF export helper                                                  */
/* ------------------------------------------------------------------ */

function exportSessionPDF(childName: string, durationSec: number) {
  const now = new Date();
  const dateStr = now.toLocaleDateString('en-GB', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  const timeStr = now.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<title>Session Report \u2014 ${childName}</title>
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:700px;margin:40px auto;color:#1a1a2e;padding:0 20px}
  h1{font-size:28px;margin-bottom:4px}
  .brand{color:#38C9F0;font-size:22px;font-weight:700;margin-bottom:24px}
  .meta{color:#666;font-size:14px;margin-bottom:28px}
  .section{margin-bottom:24px}
  .section h2{font-size:18px;margin-bottom:8px;border-bottom:1px solid #e0e0e0;padding-bottom:4px}
  .bar{display:flex;height:16px;border-radius:8px;overflow:hidden;margin:8px 0}
  .bar div{height:100%}
  ul{padding-left:20px}
  li{margin-bottom:4px;font-size:14px}
  .footer{margin-top:40px;color:#999;font-size:12px;text-align:center;border-top:1px solid #e0e0e0;padding-top:16px}
  @media print{body{margin:20px}}
</style>
</head>
<body>
  <div class="brand">HarmonyAlert</div>
  <h1>Session Report \u2014 ${childName}</h1>
  <div class="meta">${dateStr} at ${timeStr} &middot; Duration: ${formatDurationLong(durationSec)}</div>

  <div class="section">
    <h2>Tone Analysis</h2>
    <p>Your tone was <strong>calm 82%</strong> of the time.</p>
    <div class="bar">
      <div style="width:82%;background:#34D399"></div>
      <div style="width:12%;background:#FBBF24"></div>
      <div style="width:6%;background:#F87171"></div>
    </div>
    <p>Best streak: 6 min 12 sec of calm tone. Moments your tone rose: 3.</p>
  </div>

  <div class="section">
    <h2>Child State During Session</h2>
    <p>${childName} was mostly calm during this session.</p>
    <div class="bar">
      <div style="width:60%;background:#34D399"></div>
      <div style="width:25%;background:#FBBF24"></div>
      <div style="width:15%;background:#F87171"></div>
    </div>
    <p>Calm 60% &middot; Uneasy 25% &middot; Frustrated 15%</p>
  </div>

  <div class="section">
    <h2>Prompts &amp; Guidance</h2>
    <p>3 prompts were shown. You responded positively to 2 of 3 (67%).</p>
    <p>Prompt acceptance rate is improving! Last session was 50%.</p>
  </div>

  <div class="section">
    <h2>Communication</h2>
    <p>${childName} used 4 signs during this session:</p>
    <ul>${MOCK_SIGNS.map(s => `<li>${s}</li>`).join('')}</ul>
  </div>

  <div class="section">
    <h2>Key Moments</h2>
    <ul>${MOCK_KEY_MOMENTS.map(m => `<li>${m}</li>`).join('')}</ul>
  </div>

  <div class="footer">Generated by HarmonyAlert &middot; harmonyalert.com</div>
</body>
</html>`;

  const w = window.open('', '_blank');
  if (w) {
    w.document.write(html);
    w.document.close();
  }
}

/* ------------------------------------------------------------------ */
/*  Component                                                          */
/* ------------------------------------------------------------------ */

export default function SessionTracker() {
  const { childProfile, addToast } = useAppStore();
  const childName = childProfile.name || 'Leo';

  /* Session state */
  const [sessionActive, setSessionActive] = useState(false);
  const [sessionStart, setSessionStart] = useState<number | null>(null);
  const [elapsed, setElapsed] = useState(0);
  const [showSummary, setShowSummary] = useState(false);
  const [finalDuration, setFinalDuration] = useState(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  /* Live mock counters */
  const promptCount = sessionActive ? Math.min(Math.floor(elapsed / 120) + 1, 5) : 0;
  const calmPct = sessionActive ? Math.max(70, 95 - Math.floor(elapsed / 30)) : 0;

  /* Timer effect */
  useEffect(() => {
    if (sessionActive && sessionStart) {
      timerRef.current = setInterval(() => {
        setElapsed(Math.floor((Date.now() - sessionStart) / 1000));
      }, 1000);
    }
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [sessionActive, sessionStart]);

  const startSession = useCallback(() => {
    const now = Date.now();
    setSessionActive(true);
    setSessionStart(now);
    setElapsed(0);
    setShowSummary(false);
    addToast('Session started — monitoring active', 'success');
  }, [addToast]);

  const endSession = useCallback(() => {
    if (timerRef.current) clearInterval(timerRef.current);
    setFinalDuration(elapsed);
    setSessionActive(false);
    setSessionStart(null);
    setShowSummary(true);
  }, [elapsed]);

  const closeSummary = useCallback(() => setShowSummary(false), []);

  /* ---------------------------------------------------------------- */
  /*  Render                                                           */
  /* ---------------------------------------------------------------- */

  return (
    <div className="space-y-4">
      {/* ---------- A) Session Control Bar ---------- */}
      <div className="bg-[#0D1B2A] border border-[#1A3A5C] rounded-2xl p-4">
        {!sessionActive ? (
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-white font-semibold text-lg">Session Tracker</h3>
              <p className="text-[#8EADC1] text-sm mt-0.5">Track a conversation with {childName}</p>
            </div>
            <button
              onClick={startSession}
              className="px-5 py-2.5 rounded-xl font-semibold text-sm text-white bg-gradient-to-r from-[#38C9F0] to-[#6C63FF] hover:opacity-90 transition-opacity"
            >
              Start Session
            </button>
          </div>
        ) : (
          <div className="flex flex-wrap items-center gap-3">
            {/* pulsing dot + timer */}
            <span className="relative flex h-3 w-3">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75" />
              <span className="relative inline-flex rounded-full h-3 w-3 bg-emerald-500" />
            </span>
            <span className="text-emerald-400 font-semibold text-sm">Session active &mdash; {formatDuration(elapsed)}</span>

            {/* live stats */}
            <span className="text-[#8EADC1] text-xs ml-auto hidden sm:inline">
              {promptCount} prompt{promptCount !== 1 ? 's' : ''} shown &middot; Tone: {calmPct}% calm
            </span>

            <button
              onClick={endSession}
              className="px-4 py-2 rounded-xl text-sm font-semibold border border-[#38C9F0] text-[#38C9F0] hover:bg-[#38C9F0]/10 transition-colors"
            >
              End Session
            </button>
          </div>
        )}
      </div>

      {/* ---------- C) Session History ---------- */}
      {!sessionActive && !showSummary && (
        <div className="space-y-2">
          <h4 className="text-[#8EADC1] text-xs font-semibold uppercase tracking-wider px-1">Recent Sessions</h4>
          {MOCK_HISTORY.map((h) => (
            <div key={h.id} className="bg-[#0D1B2A] border border-[#1A3A5C] rounded-xl px-4 py-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-sm">
              <span className="text-white font-medium">{h.label}</span>
              <span className="text-[#8EADC1]">{h.duration}</span>
              <span className="text-emerald-400">{h.calm}% calm</span>
              <span className="text-[#8EADC1]">{h.prompts} prompt{h.prompts !== 1 ? 's' : ''}</span>
              {h.extra && <span className="text-[#38C9F0] text-xs">{h.extra}</span>}
            </div>
          ))}
        </div>
      )}

      {/* ---------- B) Session Summary Overlay ---------- */}
      {showSummary && (
        <div className="fixed inset-0 z-[150] bg-[#060E1C]/95 backdrop-blur-sm overflow-y-auto">
          <div className="max-w-lg mx-auto px-4 py-8 space-y-6">
            {/* Header */}
            <div className="text-center">
              <div className="inline-flex items-center gap-2 bg-emerald-500/15 text-emerald-400 px-4 py-1.5 rounded-full text-sm font-semibold mb-3">
                Session Complete &#10003;
              </div>
              <p className="text-[#8EADC1] text-sm">Duration: {formatDurationLong(finalDuration)}</p>
            </div>

            {/* Tone Analysis */}
            <div className="bg-[#0D1B2A] border border-[#1A3A5C] rounded-2xl p-5 space-y-3">
              <h4 className="text-white font-semibold">Tone Analysis</h4>
              <p className="text-[#8EADC1] text-sm">Your tone was calm <span className="text-emerald-400 font-semibold">82%</span> of the time</p>
              {/* bar */}
              <div className="flex h-3 rounded-full overflow-hidden">
                <div className="bg-emerald-400" style={{ width: '82%' }} />
                <div className="bg-amber-400" style={{ width: '12%' }} />
                <div className="bg-red-400" style={{ width: '6%' }} />
              </div>
              <div className="flex text-xs text-[#8EADC1] gap-4">
                <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-emerald-400 inline-block" /> Calm 82%</span>
                <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-amber-400 inline-block" /> Moderate 12%</span>
                <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-red-400 inline-block" /> Elevated 6%</span>
              </div>
              <p className="text-sm text-[#8EADC1]">Best streak: <span className="text-white font-medium">6 min 12 sec</span> of calm tone &#11088;</p>
              <p className="text-sm text-[#8EADC1]">Moments your tone rose: <span className="text-white font-medium">3</span></p>
            </div>

            {/* Child State */}
            <div className="bg-[#0D1B2A] border border-[#1A3A5C] rounded-2xl p-5 space-y-3">
              <h4 className="text-white font-semibold">Child State During Session</h4>
              <p className="text-[#8EADC1] text-sm">{childName} was mostly <span className="text-emerald-400 font-semibold">calm</span> during this session</p>
              <div className="flex h-3 rounded-full overflow-hidden">
                <div className="bg-emerald-400" style={{ width: '60%' }} />
                <div className="bg-amber-400" style={{ width: '25%' }} />
                <div className="bg-red-400" style={{ width: '15%' }} />
              </div>
              <div className="flex text-xs text-[#8EADC1] gap-4">
                <span>Calm 60%</span>
                <span>Uneasy 25%</span>
                <span>Frustrated 15%</span>
              </div>
            </div>

            {/* Prompts & Guidance */}
            <div className="bg-[#0D1B2A] border border-[#1A3A5C] rounded-2xl p-5 space-y-2">
              <h4 className="text-white font-semibold">Prompts &amp; Guidance</h4>
              <p className="text-[#8EADC1] text-sm">3 prompts were shown</p>
              <p className="text-[#8EADC1] text-sm">You responded positively to <span className="text-white font-medium">2 of 3 (67%)</span></p>
              <p className="text-emerald-400 text-sm font-medium">Prompt acceptance rate is improving! Last session was 50%.</p>
            </div>

            {/* Communication */}
            <div className="bg-[#0D1B2A] border border-[#1A3A5C] rounded-2xl p-5 space-y-2">
              <h4 className="text-white font-semibold">Communication</h4>
              <p className="text-[#8EADC1] text-sm">{childName} used <span className="text-white font-medium">4 signs</span> during this session</p>
              <div className="flex flex-wrap gap-2 mt-1">
                {MOCK_SIGNS.map((s) => (
                  <span key={s} className="bg-[#1A3A5C] text-[#38C9F0] text-xs px-3 py-1 rounded-full">{s}</span>
                ))}
              </div>
            </div>

            {/* Key Moments */}
            <div className="bg-[#0D1B2A] border border-[#1A3A5C] rounded-2xl p-5 space-y-2">
              <h4 className="text-white font-semibold">Key Moments</h4>
              <ul className="space-y-1.5">
                {MOCK_KEY_MOMENTS.map((m, i) => (
                  <li key={i} className="text-[#8EADC1] text-sm flex gap-2">
                    <span className="text-[#38C9F0] shrink-0">&bull;</span>
                    {m}
                  </li>
                ))}
              </ul>
            </div>

            {/* Actions */}
            <div className="flex flex-col gap-3 pt-2">
              <button
                onClick={() => exportSessionPDF(childName, finalDuration)}
                className="w-full py-3 rounded-xl font-semibold text-sm bg-gradient-to-r from-[#38C9F0] to-[#6C63FF] text-white hover:opacity-90 transition-opacity"
              >
                &#128196; Export as PDF
              </button>
              <button
                onClick={() => addToast('Session shared with therapist', 'success')}
                className="w-full py-3 rounded-xl font-semibold text-sm border border-[#38C9F0] text-[#38C9F0] hover:bg-[#38C9F0]/10 transition-colors"
              >
                &#128228; Share with Therapist
              </button>
              <button
                onClick={closeSummary}
                className="w-full py-3 rounded-xl font-semibold text-sm text-[#8EADC1] hover:text-white transition-colors"
              >
                Done
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
